#!/bin/bash -x
set -e

BRANCH=$(git branch | grep \* | cut -d ' ' -f2)
GIT_SHA=$(git rev-parse --short HEAD)
VERSION="0.1.0-${BRANCH}-${GIT_SHA}"
docker build -t quay.io/weightwatchers/fastly-to-insights:${VERSION} .
docker push quay.io/weightwatchers/fastly-to-insights:${VERSION}
